services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vie-mp3-frontend
    restart: always
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    env_file:
      - .env
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
