const routes = {
  album: '/album',
  analytic: '/analytic',
  alnums: '/albums',
  artist: '/artist',
  favoriteAlbums: '/favorite-albums',
  favoriteArtists: '/favorite-artists',
  favoriteSongs: '/favorite-songs',
  genre: '/genre',
  genres: '/genres',
  history: '/history',
  home: '/',
  library: '/library',
  login: '/login',
  lyris: '/lyris',
  myAlbums: '/my-albums',
  mySongs: '/my-songs',
  otp: '/otp',
  playlist: '/playlist',
  playlists: '/playlists',
  profile: '/profile',
  register: '/register',
  // searched: '/searched',
  song: '/song',

  manage: '/manage',
  manageAccounts: '/manage/accounts',
  manageArtists: '/manage/artists',
  manageAlbums: '/manage/albums',
  manageSongs: '/manage/songs',
  manageGenres: '/manage/genres',
  managePlaylists: '/manage/playlists',
  manageMemberships: '/manage/memberships',
  manageRevenues: '/manage/revenue',
};

export default routes;
