const routes = {
  album: 'album',
  artist: '/artist',
  favoriteAlbums: '/favorite-albums',
  favoriteArtists: '/favorite-artists',
  favoriteSongs: '/favorite-songs',
  genre: '/genre',
  genres: '/genres',
  history: '/history',
  home: '/',
  library: '/library',
  login: '/login',
  lyris: '/lyris',
  myAlbums: '/my-albums',
  mySongs: '/my-songs',
  otp: '/otp',
  playlist: '/playlist',
  profile: '/profile',
  register: '/register',
  searched: '/searched',
  song: '/song',
  upload: '/upload',
};

export default routes;
